---

steps:
  # cacheがあればpullする
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - 'docker pull gcr.io/$PROJECT_ID/kurasawatest:$_TAG_NAME || true'
  # build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --cache-from
      - gcr.io/$PROJECT_ID/kurasawatest:$_TAG_NAME
      - -t
      - gcr.io/$PROJECT_ID/kurasawatest:$_TAG_NAME
      - .
  # GCRへpush
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/kurasawatest:$_TAG_NAME
  # CloudRunへdeploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - kurasawatest
      - --image
      - gcr.io/$PROJECT_ID/kurasawatest:$_TAG_NAME
      - --region
      - asia-northeast1
      - --platform
      - managed
options:
  substitutionOption: MUST_MATCH
