---

steps:
  # cacheがあればpullする
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - 'docker pull gcr.io/$PROJECT_ID/kurasawatest:$_TAG_NAME || true'
  # build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file config/cloudbuild.yml
      - --cache-from
      - gcr.io/$PROJECT_ID/kurasawatest:$_TAG_NAME
      - -t
      - gcr.io/$PROJECT_ID/kurasawatest:$_TAG_NAME
      - .
  # GCRへpush
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/kurasawatest:$_TAG_NAME
options:
  substitutionOption: MUST_MATCH
